[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/dayfox.toml"]
# import = ["~/.config/alacritty/themes/default.toml"]

[font]
size = 15

[font.offset]
y = 8

[font.glyph_offset]
y = 9

[font.normal]
family = "Hack Nerd Font"

[window]
opacity = 0.98
decorations = "buttonless"

[window.padding]
x = 5
y = 5

[window.dimensions]
columns = 120
lines = 40

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Never"

[env]
TERM = "xterm-256color"

[scrolling]
history = 2000
# auto_scroll = true

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001BF"

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001BB"

# [terminal.shell]
# program = "/usr/bin/tmux"
# args = ["new-session", "-A", "-D", "-s", "main"]

