
[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[general]
live_config_reload = true

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Never"

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.glyph_offset]
y = 9

[font.normal]
family = "Hack Nerd Font"

[font.offset]
y = 8

